"""Test that all fields can be selected and synced."""
from base import PardotBaseTest
from tap_tester.base_suite_tests.all_fields_test import AllFieldsTest


class PardotAllFieldsTest(AllFieldsTest, PardotBaseTest):
    """Test that all fields for each stream are replicated."""

    # Fields defined in schema but not populated in the demo account data.
    KEYS_WITH_NO_DATA = {
        "prospects": {
            "crm_last_sync",
            "comments",
            "fax",
            "notes",
            "is_starred",
            "crm_url",
            "crm_account_fid",
            "password",
            "recent_interaction",
        },
    }

    @staticmethod
    def name():
        return "tap_tester_pardot_all_fields_test"

    def streams_to_test(self):
        streams_to_exclude = {
            # Child of visitors; parent has no data in demo account.
            "visits",

            # No data in demo account: auto-generated by website tracking.
            "visitors",
            "visitor_activities",

            # No data in demo account: managed by Salesforce CRM connector.
            "opportunities",
            "prospect_accounts",

            # No data in demo account: requires email campaigns to be sent and clicked.
            "email_clicks",
        }
        return self.expected_stream_names().difference(streams_to_exclude)
