"""Test that all fields can be selected and synced."""
from base import PardotBaseTest
from tap_tester.base_suite_tests.all_fields_test import AllFieldsTest


class PardotAllFieldsTest(AllFieldsTest, PardotBaseTest):
    """Test that all fields for each stream are replicated."""

    @staticmethod
    def name():
        return "tap_tester_pardot_all_fields_test"

    def streams_to_test(self):
        # Exclude large/child streams and streams with no data in demo account.
        # visitors/visitor_activities: auto-generated by website tracking
        # opportunities/prospect_accounts: managed by Salesforce CRM connector
        # email_clicks: requires email campaigns to be sent and clicked
        streams_to_exclude = {
            "visits", "list_memberships", "prospects",
            "visitors", "visitor_activities", "email_clicks",
            "opportunities", "prospect_accounts",
        }
        return self.expected_stream_names().difference(streams_to_exclude)
