"""Test that all fields can be selected and synced."""
from base import PardotBaseTest
from tap_tester.base_suite_tests.all_fields_test import AllFieldsTest


class PardotAllFieldsTest(AllFieldsTest, PardotBaseTest):
    """Test that all fields for each stream are replicated."""

    @staticmethod
    def name():
        return "tap_tester_pardot_all_fields_test"

    def streams_to_test(self):
        streams_to_exclude = {
            # Child of visitors; parent has no data in demo account.
            "visits",
            # Child of lists; no membership data in demo account.
            "list_memberships",
            # High volume with full date range; no all-fields data in recent window.
            "prospects",

            # No data in demo account: auto-generated by website tracking.
            "visitors",
            "visitor_activities",

            # No data in demo account: managed by Salesforce CRM connector.
            "opportunities",
            "prospect_accounts",

            # No data in demo account: requires email campaigns to be sent and clicked.
            "email_clicks",
        }
        return self.expected_stream_names().difference(streams_to_exclude)
